Trust Reg - dotnet sdk
Dentity-Development/dentity-ecosystems-sdk pull request #105
Opened 2021-08-18 19:52 UTC by tmarkovski

2021-08-22 22:57 UTC, fundthmcalculus approved these changes
Looks good. I'm happy to do the other SDKs.

2021-08-23 19:49 UTC, michaeldboyd requested changes

2021-08-23 19:49 UTC, michaeldboyd commented on dotnet/Source/Trinsic/TrustRegistryService.cs
> +        public async Task RegisterGovernanceFramework(string governanceFrameworkUri, string description)
I think we should leave off the `_Uri` suffix on the `governanceFrameworkUri` here so that it matches the same naming conventions as the other endpoints below.

2021-08-23 19:49 UTC, michaeldboyd commented on dotnet/Source/Trinsic/TrustRegistryService.cs
> +        public async Task CheckIssuerStatus(string issuerDid, string presentationType, string governanceFramework)
Shouldn't this be `credentialType`?

2021-08-23 19:49 UTC, michaeldboyd commented on dotnet/Source/Trinsic/TrustRegistryService.cs
> +
Are we missing a `CheckVerifierStatus` endpoint?

2021-08-26 15:10 UTC, merged