Remove default ecosystem from sdk and docs
Dentity-Development/dentity-ecosystems-sdk pull request #1192
Opened 2022-12-06 17:32 UTC by tmarkovski

2022-12-06 19:03 UTC, janpieterz approved these changes
LGTM :)

2022-12-06 20:38 UTC, fundthmcalculus requested changes
Error due to ecosystem being required since these are tested samples.

2022-12-06 22:50 UTC, tmarkovski commented
There's a conflict of interests.

2022-12-08 14:01 UTC, fundthmcalculus approved these changes

2022-12-08 14:06 UTC, merged