Python calls
Dentity-Development/dentity-ecosystems-sdk pull request #125
Opened 2021-09-20 13:13 UTC by michaeldboyd

2021-09-20 16:28 UTC, tmarkovski approved these changes

2021-09-22 20:16 UTC, fundthmcalculus requested changes
See comments, but looks good!

2021-09-22 20:16 UTC, fundthmcalculus commented on docs/concepts/index.md
> +- [ ] Objective C (iOS)
`Swift`, not `Objective C`.

2021-09-22 20:16 UTC, fundthmcalculus commented on docs/reference/services/provider-service.md
> +    ```
Let me add the code for this. Dictionaries use `:`.

2021-09-22 20:16 UTC, fundthmcalculus commented on docs/reference/services/wallet-service.md
> +    ```
Yes

2021-09-22 20:16 UTC, fundthmcalculus commented on docs/reference/services/wallet-service.md
> +    ```
Yes

2021-09-22 20:16 UTC, fundthmcalculus commented on docs/reference/services/wallet-service.md
> +    ```
Yes, that should be a `dict`ionary type.

2021-09-22 20:16 UTC, fundthmcalculus commented on docs/reference/services/wallet-service.md
> +
Takes a string as an argument
On that note- @tmarkovski how do we prevent SQL injection attacks?

2021-09-22 20:16 UTC, fundthmcalculus commented on docs/reference/services/wallet-service.md
> +    ```
Let me inject the right code

2021-09-22 20:16 UTC, fundthmcalculus commented on mkdocs.yml
>      - C#: walkthrough/vaccination-net.md
Call it `CSharp` so that .yml isn't broken?

2021-09-22 20:16 UTC, fundthmcalculus commented on docs/walkthrough/vaccination-python.md
> +    ```
We should inject this from the actual file.

2021-09-22 20:16 UTC, fundthmcalculus commented on docs/walkthrough/vaccination-python.md
> +    ```
Inject this from the actual file.

2021-09-22 20:16 UTC, fundthmcalculus commented on docs/walkthrough/vaccination-python.md
> +```
Would this be better done with a doc comment in Python?

2021-09-22 23:36 UTC, michaeldboyd commented on docs/walkthrough/vaccination-python.md
> +```
Yeah, I definitely think your comments on the unit test could pretty easily be used as documentation instead of the code samples with surrounding documentation here.

2021-10-10 18:18 UTC, tmarkovski commented
@michaeldboyd @fundthmcalculus What's the status on this PR? Can we get it in? Any updates required? Can we address them?
I'd like to ad Trust Reg documentation for IIW demo this week. This is "somewhat" blocking.

2021-10-10 21:55 UTC, fundthmcalculus commented
I will address them later tonight or tomorrow.

On Sun, Oct 10, 2021, 14:19 Tomislav Markovski ***@***.***>
wrote:

> @michaeldboyd <https://github.com/michaeldboyd> @fundthmcalculus
> <https://github.com/fundthmcalculus> What's the status on this PR? Can we
> get it in? Any updates required? Can we address them?
> I'd like to ad Trust Reg documentation for IIW demo this week. This is
> "somewhat" blocking.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/trinsic-id/sdk/pull/125#issuecomment-939528884>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AD7QPF75K5PEXNUKLKQKYADUGHKJZANCNFSM5EL52ISA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-10-13 18:22 UTC, fundthmcalculus commented on docs/reference/services/provider-service.md
> +    }
```suggestion
    request = {
        "email" : "admin@faber.edu",
        "participant" : provider_services.Organization
    } 
```

2021-10-13 18:22 UTC, fundthmcalculus approved these changes

2021-10-22 14:12 UTC, fundthmcalculus approved these changes

2021-10-22 21:03 UTC, merged