Updated .NET samples
Dentity-Development/dentity-ecosystems-sdk pull request #1353
Opened 2023-03-22 22:08 UTC by geel9

- Updated .NET Samples
	- Does not include `SearchRegistry` sample -- @tmarkovski please advise (current samples don't include an example query)
- Uses following baseline parameters:
	- Ecosystem name: `my-ecosystem`
	- Template:
		- Name: `An Example Credential` / `an-example-credential` / `urn:template:my-ecosystem:an-example-credential`
		- Fields: `firstName`, `lastName`, `age`
	- Wallet email: `jane.doe@example.com`
	- Credential ID: `urn:uuid:7afd0191-9656-3a51-c12f-44ecfbb5a829`
	- Revocation ID: `urn:revocation-registry:my-ecosystem:AD9wKZCr4zVxat1XSawScD#42`
	- Trust Registry ID: `urn:egf:my-ecosystem:1297e60abb3b425faaaf0f0a551aae2c`

2023-03-23 12:43 UTC, fundthmcalculus requested changes
Overall, I approve of the code snippets. Let's not conflate the removal of deprecated endpoints from the docs with code snippet creation.

2023-03-23 12:43 UTC, fundthmcalculus commented on docs/reference/services/provider-service.md
> -
Why are these removed?

2023-03-23 12:43 UTC, fundthmcalculus commented on docs/reference/services/provider-service.md
> ----
Do we want to remove these yet?

2023-03-23 14:34 UTC, geel9 commented on docs/reference/services/provider-service.md
> -
My understanding is we had agreed at some point that these should not be part of the public-facing SDK but rather the job of the Dashboard -- I can add samples back in if we like but I'd prefer to move forward with porting them out of the SDK.

2023-03-23 14:36 UTC, geel9 commented on docs/reference/services/provider-service.md
> ----
These haven't been called a single time in the past month and we plan to remove them shortly -- might as well bite the bullet and not perform the work of documenting endpoints that are effectively already dead.

2023-03-23 14:36 UTC, geel9 commented
> Overall, I approve of the code snippets. Let's not conflate the removal of deprecated endpoints from the docs with code snippet creation.

Fair -- I'll make a separate PR and the discussion can live there

2023-03-23 14:55 UTC, fundthmcalculus commented on docs/reference/services/provider-service.md
> -
Agreed. Let's remove these.

2023-03-23 14:55 UTC, fundthmcalculus commented on docs/reference/services/provider-service.md
> ----
@janpieterz thoughts?

2023-04-13 14:40 UTC, geel9 commented
Moving to draft as we are pausing this work

2023-09-07 19:15 UTC, tmarkovski commented
Bump @geel9 @fundthmcalculus . We still want this in or can it be closed?

2024-06-27 13:46 UTC, closed without merging