Update Trust Registry Service docs
Dentity-Development/dentity-ecosystems-sdk pull request #1426
Opened 2023-06-07 15:35 UTC by chiarapaskulin

2023-06-07 16:37 UTC, lucasamonrc approved these changes

2023-06-07 17:15 UTC, geel9 requested changes

2023-06-07 17:15 UTC, geel9 commented on docs/reference/services/trust-registry-service.md
> +The Governance API exposes functionalities for managing [Trust Registries](/learn/concepts/trust-registries).
```suggestion
The Governance API exposes functionality for managing your Ecosystem's [Trust Registry](/learn/concepts/trust-registries).
```

2023-06-07 17:15 UTC, geel9 commented on docs/reference/services/trust-registry-service.md
> +A Trust Registry is a list of authorized issuers for the various credential types within an ecosystem. Each ecosystem has a Trust Registry and you can use the following API calls to manage its truste
```suggestion
A Trust Registry is a list of authorized issuers for the various credential types within an ecosystem.
```

I think less is more, here

2023-06-08 10:34 UTC, chiarapaskulin commented on docs/reference/services/credential-service.md
The redirect was breaking in the docs with the ".md"

2023-06-08 10:44 UTC, chiarapaskulin commented on docs/reference/services/credential-service.md
> +See [Trust Registry Service](/reference/services/trust-registry-service) for more information on managing your ecosystem's governance.
Redirect in the website was failing with the ".md" included.

2023-06-08 10:45 UTC, chiarapaskulin commented on docs/reference/services/credential-service.md
>  the given governance framework. The framework identifier will be in the `issuer.trustRegistry` field.
Is the framework identifier still stored in the credential after the related API changes?

2023-06-09 19:39 UTC, geel9 commented on docs/reference/services/credential-service.md
>  the given governance framework. The framework identifier will be in the `issuer.trustRegistry` field.
Yes, it is

2023-06-09 19:39 UTC, geel9 approved these changes

2023-06-09 19:41 UTC, fundthmcalculus approved these changes

2023-06-09 19:46 UTC, merged