Docs improvements
Dentity-Development/dentity-ecosystems-sdk pull request #1488
Opened 2023-09-04 19:52 UTC by chiarapaskulin

2023-09-04 19:56 UTC, chiarapaskulin commented
Some changes included here don't belong to this PR. They will disappear once we merge [#2730](https://github.com/trinsic-id/server/pull/2730).

2023-09-06 20:18 UTC, chiarapaskulin commented
Not ready for review yet. Just marked it as ready for review to see mewmba's docs previews :) (thanks steven @fundthmcalculus for those! <3 )

2023-09-07 16:27 UTC, tmarkovski commented
Why isn't the docs preview action firing?

2023-09-07 16:28 UTC, tmarkovski commented on docs/examples/1-issue-direct-send.md
> -:   `templateId` is a required field and refers to the template ID that we want to use.
Any reason why you chose to use `<li>` as opposed to the definition indented list that comes with MkDocs?

2023-09-07 16:29 UTC, tmarkovski commented on docs/examples/1-issue-direct-send.md
> +Finally, we can just send the credentil to the user's wallet by specifying its email address. If you want to send an email notification that a credential has been sent to the user's wallet, just set
```suggestion
Finally, we can just send the credential to the user's wallet by specifying its email address. If you want to send an email notification that a credential has been sent to the user's wallet, just set `sendNotification` as true.
```

2023-09-07 16:29 UTC, fundthmcalculus commented
> Why isn't the docs preview action firing?

I need to get the new mkdocs-material token in.

2023-09-07 19:09 UTC, lucasamonrc reviewed
I noticed the same things that @tmarkovski pointed out so I will not give a explicit approval for now. But once those comments are addressed I'll approve it.

2023-09-07 20:02 UTC, fundthmcalculus commented
@chiarapaskulin your demo docs site is up!

2023-09-08 19:23 UTC, tmarkovski commented on docs/examples/1-issue-direct-send.md
> +(You can obtain Auth Token from the [Dashboard <small>:material-open-in-new:</small>](https://dashboard.trinsic.id){targer=_blank} by clicking on the View Auth Token button in the Home page.)
```suggestion
(You can obtain an Auth Token from the [Dashboard <small>:material-open-in-new:</small>](https://dashboard.trinsic.id){targer=_blank} by clicking on the View Auth Token button in the Home page.)
```

2023-09-11 14:32 UTC, tmarkovski approved these changes

2023-09-15 14:43 UTC, chiarapaskulin commented on docs/examples/1-issue-direct-send.md
> -:   `templateId` is a required field and refers to the template ID that we want to use.
Oh, I used it to have the dots in the list
![image](https://github.com/trinsic-id/sdk/assets/44075372/2b641a2a-81d4-4f73-bc84-0c5a1ff5943f)
But I found out I can use " - " (MkDocs docmark) to have the dots! :)
Thanks!

2023-09-15 16:49 UTC, lucasamonrc requested changes

2023-09-15 16:49 UTC, lucasamonrc commented on mkdocs.yml
> -  - Examples: examples/index.md
Please, restore this line. We need to have examples in the navigation.

2023-09-15 17:02 UTC, chiarapaskulin commented on mkdocs.yml
> -  - Examples: examples/index.md
Ops, that's an old change I reverted but somehow is still here... Thanks!

2023-09-17 03:16 UTC, lucasamonrc approved these changes

2023-09-19 20:04 UTC, lucasamonrc approved these changes

2023-09-22 17:11 UTC, merged