Wallet API Docs Improvements
Dentity-Development/dentity-ecosystems-sdk pull request #1553
Opened 2023-10-20 17:31 UTC by chiarapaskulin

2023-10-23 17:47 UTC, lucasamonrc reviewed
Something fishy is going on
<img width="1317" alt="Screenshot 2023-10-23 at 12 46 54 PM" src="https://github.com/trinsic-id/sdk/assets/53352488/666d56de-cf6d-4d44-b79e-38ac6d0adf7c">

2023-10-23 17:48 UTC, chiarapaskulin commented
> Something fishy is going on <img alt="Screenshot 2023-10-23 at 12 46 54 PM" width="1317" src="https://user-images.githubusercontent.com/53352488/277426789-666d56de-cf6d-4d44-b79e-38ac6d0adf7c.png">

Yeah, I know. I'll finish it and then ask for a review hahah

2023-10-23 17:49 UTC, lucasamonrc commented
> > Something fishy is going on <img alt="Screenshot 2023-10-23 at 12 46 54 PM" width="1317" src="https://user-images.githubusercontent.com/53352488/277426789-666d56de-cf6d-4d44-b79e-38ac6d0adf7c.png">
> 
> Yeah, I know. I'll finish it and then ask for a review hahah

Nevermind, it was an old preview. Looks good so far.

2023-10-24 18:11 UTC, janpieterz requested changes, later dismissed

2023-10-24 18:11 UTC, janpieterz commented on docs/reference/services/wallet-service.md
> +    - Returning users that have lost their previous session and require new auth token
```suggestion
    - Returning users that have lost their previous session and require a new auth token
```

2023-10-24 18:11 UTC, janpieterz commented on docs/reference/services/wallet-service.md
> +    - Users want to log in to a different device using their email or phone number
```suggestion
    - Users that want to log in to a different device using their email or phone number
```

2023-10-24 18:11 UTC, janpieterz commented on docs/reference/services/wallet-service.md
> +        // var options = new TrinsicOptions { AuthToken = AuthenticateConfirmResponse.AuthToken };
```suggestion
        // var options = new TrinsicOptions { AuthToken = authenticateConfirmResponse.AuthToken };
```

2023-10-24 18:11 UTC, janpieterz commented on docs/reference/services/wallet-service.md
> +This service is used to attach external identity, such as email or phone number, to a wallet. The purpose of this process is to allow
```suggestion
This service is used to attach an external identity, such as an email or a phone number, to a wallet. The purpose of this process is to allow
```

2023-10-24 18:11 UTC, janpieterz commented on docs/reference/services/wallet-service.md
> +This endpoint requires that the wallet user has previously added at least one external identity using the above endpoints.
```suggestion
This endpoint requires that the wallet user has previously added at least one external identity using `AddExternalIdentity` calls below.
```

Or mention below, since they are below in this document. But probably better to not mention above/below as it'd be lost in a restructure of the docs.

2023-10-24 18:14 UTC, tmarkovski commented on docs/reference/services/wallet-service.md
> -        using Trinsic;
I know most IDEs will help resolve namespaces, but I feel it is important that an example shows the basic namespace opening.

Any reasons why you removed this?

2023-10-24 18:15 UTC, tmarkovski commented on docs/reference/services/wallet-service.md
> +        // Step 1 - initiate authentication challenge
Same comment here on removing using statements.

2023-10-24 18:25 UTC, chiarapaskulin commented on docs/reference/services/wallet-service.md
> -        using Trinsic;
@tmarkovski this is already documented in other parts of the docs. otherwise, we'd have to add the "using Trinsic" and the service instantiation in all the samples. as far as I understand, they're supposed to be snippets specifically of how the methods are called.

2023-10-24 18:26 UTC, chiarapaskulin commented on docs/reference/services/wallet-service.md
> +        // Step 1 - initiate authentication challenge
Answered in the other comment hahah

2023-10-24 18:29 UTC, chiarapaskulin commented on docs/reference/services/wallet-service.md
> +This endpoint requires that the wallet user has previously added at least one external identity using the above endpoints.
thanks! changed it to "calls" :)

2023-10-24 18:58 UTC, lucasamonrc commented on docs/reference/services/wallet-service.md
>          // }
I would argue that this can be omitted since we already make the response model available in one of the other tabs. Unless you feel strongly about this, I'd remove it.

2023-10-24 18:59 UTC, lucasamonrc commented on docs/reference/services/wallet-service.md
>          // }
This comment apply to other places that also include a similar comment in the snippet

2023-10-24 19:01 UTC, chiarapaskulin commented on docs/reference/services/wallet-service.md
>          // }
I agree with you :) Will remove them

2023-10-24 19:08 UTC, lucasamonrc approved these changes
I'd wait for @janpieterz or @tmarkovski before merging just to be more thorough since I think docs work is a highly subjective business (your call). Looks good to me.

2023-10-24 20:13 UTC, janpieterz approved these changes
Looks good to me :)

2023-10-25 14:15 UTC, merged