docs: Add documentation for the multi-ecosystems-lookup work
Dentity-Development/dentity-ecosystems-sdk pull request #1575
Opened 2023-11-15 21:02 UTC by lucasamonrc

2023-11-21 16:35 UTC, janpieterz requested changes
Let's change the focus from `result_vp` to normalized data parts and highlight the painpoints of `result_vp` usage more/better + add structure of normalized data.

2023-11-21 16:35 UTC, janpieterz commented on docs/reference/services/connect-service.md
>  Below is an example JSON document representing the structure of the output of a Session created with a single Verification of type `GOVERNMENT_ID`:
We probably want to showcase the complete response and, notably, the `result_vp` has become a lot less important (it'll be different for each credential, so we can't push e.g. a "givenName" field.

2023-11-21 16:35 UTC, janpieterz commented on docs/reference/services/connect-service.md
> +If a verification is successful, its {{ field_ref("GetSessionResponse", "session.state") }}  will be {{ field_ref("GetSessionResponse", "session.state.IDV_SUCCESS") }}, and the resultant data will be
We should add a strong note about the `result_vp` containing different proofs depending on the issuer, where-as the normalized data _does not_. We don't really want people to use the `result_vp` unless they're absolutely sure what they're doing.

2023-11-21 16:35 UTC, janpieterz commented on docs/reference/services/connect-service.md
>  If the Session has been completed successfully, the results will be available in the {{ field_ref("GetSessionResponse", "session.result_vp") }} field of the returned Session. See [Get Verification Re
We should flip this and add a bit about how the `result_vp` will be different depending on issuer as well as how it's better to use the normalized data

2023-11-22 23:31 UTC, lucasamonrc commented
I'm closing, we will revisit the docs this following week in preparation for our launch.

2023-11-22 23:32 UTC, lucasamonrc commented
Closing this, we will address all of these points when we prepare our docs for the product launch in the next week.

2023-11-22 23:32 UTC, closed without merging