consolidated walkthrough
Dentity-Development/dentity-ecosystems-sdk pull request #383
Opened 2022-01-18 16:19 UTC by michaeldboyd

- Support for account endpoints + bugfixes (#223)
- security rough draft
- added intro and wallets
- passes
- Template sub command
- Templates proto
- Add missing impl
- Create template impl
- Reorder input
- Create works
- Template get
- Remove warnings
- List templates
- Search
- Credential status
- get and update status commands
- Test end to end
- update structure
- update docs
- consolidate vaccination sample
- added overview of features
- added template description

2022-01-18 16:20 UTC, tmarkovski commented on cli/README.md
> +- run `rustup default nightly`
Are you sure nightly is still required? I think it isn't anymore

2022-01-18 16:20 UTC, tmarkovski commented on docs/dotnet/index.md
> +    Xamarin targets for iOS and Android are fully supported using the same package dependencies. Support for Blazor in Web Assembly will be available in a future release.
This is not needed, all .NET runtimes are now supported.

2022-01-18 16:21 UTC, tmarkovski commented on docs/dotnet/index.md
> +    PM> Install-Package Okapi.Net
This is not required, Okapi.Net transitively brings everything it needs now. Check dotnet/README

2022-01-18 16:21 UTC, tmarkovski commented on docs/dotnet/index.md
> +    The package `Okapi.Net` is already a dependency of `Trinsic` package, but we must add explicitly to bring in static library dependencies.
Not anymore.

2022-01-18 16:22 UTC, tmarkovski commented on docs/dotnet/index.md
> +var service = new WalletService();
I think wallet service ctor needs an account profile now.

2022-01-18 16:22 UTC, tmarkovski commented on docs/learn/templates.md
> +        "required": true
this field doesn't exist

2022-01-18 16:23 UTC, tmarkovski commented on docs/learn/templates.md
> +        id: "urn:template:__default:review",
let's replace `__default` with some friendly app slug for ecosystem... like `my-company` or similar.

2022-01-18 16:23 UTC, michaeldboyd commented on cli/README.md
> +- run `rustup default nightly`
the last time I ran a build from source I had to install the nightly build. It was hard to find the magic command so I just added it here. Not sure if it's still required. If you can confirm it's not I'll happily remove it

2022-01-18 16:24 UTC, tmarkovski commented on docs/reference/services/credential-service.md
> +    trinsic issuer issue --document <INPUT_JSONLD_FILE> --out <OUTPUT_FILE>
This might be using `vc` sub-command now.

2022-01-18 16:24 UTC, tmarkovski commented on docs/reference/services/credential-service.md
> +    trinsic issuer verify-proof --proof-document <JSONLD_FILE>
`vc`

2022-01-18 16:25 UTC, michaeldboyd commented on docs/dotnet/index.md
> +    Xamarin targets for iOS and Android are fully supported using the same package dependencies. Support for Blazor in Web Assembly will be available in a future release.
Awesome! Any suggestions on how to direct devs to them? Just send them to the respective sample apps?

2022-01-18 16:30 UTC, fundthmcalculus requested changes

2022-01-18 16:30 UTC, fundthmcalculus commented on overrides/main.html
> +<p>Join <a href="https://trinsic.typeform.com/to/EIO26xym">Trinsic Ecosystems Beta!</a></p>
new location for the docs?

2022-01-18 16:30 UTC, fundthmcalculus commented on mkdocs.yml
> +      title_mode: none
tabbed is required for the code injection.

2022-01-18 16:30 UTC, fundthmcalculus commented on docs/reference/services/template-service.md
> +    ```
@lucasamonrc I can help you flesh this out.

2022-01-18 16:30 UTC, fundthmcalculus commented on docs/dotnet/index.md
> +    The package `Okapi.Net` is already a dependency of `Trinsic` package, but we must add explicitly to bring in static library dependencies.
we still have to install the okapi native libraries, don't we?

2022-01-18 16:30 UTC, fundthmcalculus commented on docs/reference/services/credential-service.md
> +    ```
In general, we should code inject rather than static type, but for this it probably doesn't matter too much.

2022-01-18 16:30 UTC, fundthmcalculus commented on docs/reference/services/credential-service.md
> +    ```
@lucasamonrc flesh this out.

2022-01-18 16:30 UTC, fundthmcalculus commented on docs/reference/services/credential-service.md
> +    ```
@lucasamonrc flesh out.

2022-01-18 16:30 UTC, fundthmcalculus commented on docs/reference/services/credential-service.md
> +    ```
@lucasamonrc flesh out.

2022-01-18 16:30 UTC, fundthmcalculus commented on docs/reference/services/credential-service.md
> +    ```
code inject @lucasamonrc

2022-01-18 16:30 UTC, fundthmcalculus commented on docs/reference/services/credential-service.md
> +    ```
@lucasamonrc code inject here.

2022-01-18 16:30 UTC, fundthmcalculus commented on docs/reference/services/template-service.md
> +    ```
@lucasamonrc flesh out please

2022-01-18 16:30 UTC, fundthmcalculus commented on docs/reference/services/template-service.md
> +    ```
@lucasamonrc flesh out.

2022-01-18 16:30 UTC, fundthmcalculus commented on docs/reference/services/template-service.md
> +    ```
@lucasamonrc flesh out.

2022-01-18 16:30 UTC, fundthmcalculus commented on docs/reference/services/template-service.md
> +    ```
@lucasamonrc complete please.

2022-01-18 16:51 UTC, fundthmcalculus commented on mkdocs.yml
> +      title_mode: none
correction, it works right now, (thumbsup).

2022-01-20 20:20 UTC, fundthmcalculus commented on docs/dotnet/index.md
> +var service = new WalletService();
it does

2022-01-20 20:20 UTC, fundthmcalculus approved these changes

2022-01-20 20:22 UTC, fundthmcalculus commented on docs/dotnet/index.md
> +    Xamarin targets for iOS and Android are fully supported using the same package dependencies. Support for Blazor in Web Assembly will be available in a future release.
```suggestion

!!! note "Supported runtimes"
    .NET targets for iOS, Android, and Blazor are fully supported using the same package dependencies via .NET 6.
```

2022-01-20 20:23 UTC, fundthmcalculus commented on docs/dotnet/index.md
> +    The package `Okapi.Net` is already a dependency of `Trinsic` package, but we must add explicitly to bring in static library dependencies.
```suggestion
```

2022-01-20 20:23 UTC, fundthmcalculus commented on docs/dotnet/index.md
> +    PM> Install-Package Okapi.Net
```suggestion
```

2022-01-20 20:24 UTC, fundthmcalculus commented on docs/dotnet/index.md
> +var service = new WalletService();
```suggestion
// WalletService requires an account profile
var accountService = new AccountService();
var accountProfile = await accountService.signIn();
var service = new WalletService(accountProfile);
```

2022-01-20 20:26 UTC, fundthmcalculus approved these changes
made a number of the requested changes in preparation for merge

2022-01-20 20:26 UTC, fundthmcalculus commented on docs/learn/templates.md
> +        "required": true
```suggestion
```

2022-01-20 20:26 UTC, fundthmcalculus commented on docs/reference/services/credential-service.md
> +    trinsic issuer verify-proof --proof-document <JSONLD_FILE>
```suggestion
    trinsic vc issuer verify-proof --proof-document <JSONLD_FILE>
```

2022-01-20 21:01 UTC, merged