go doc updates with some dotnet doc updates as well.
Dentity-Development/dentity-ecosystems-sdk pull request #400
Opened 2022-01-24 23:18 UTC by fundthmcalculus

2022-01-24 23:35 UTC, sethjback requested changes

2022-01-24 23:35 UTC, sethjback commented on docs/go/index.md
> +go install https://github.com/trinsic-id/sdk/go
the `go get` and `go install` commands all leave off the URL scheme (`https://` )

2022-01-24 23:35 UTC, sethjback commented on devops/build_sdks.py
> +    doc_path = abspath(join(get_language_dir('docs'), 'reference', 'go'))
I think this is great to have a readme in the repo. - the next step would be to comment the code so that public [go docs](https://pkg.go.dev/search?q=trinsic) and the generated readme have more detailed information.

This can be done later - I've always found coding with the volume of comments required to make pretty documentation to be a pain :-), but it looks good and documentation at https://pkg.go.dev will be one of the first places golang dev will look.

2022-01-24 23:37 UTC, sethjback commented on devops/build_sdks.py
> +    doc_path = abspath(join(get_language_dir('docs'), 'reference', 'go'))
This is a comment only - no changes requested here

2022-01-25 01:21 UTC, fundthmcalculus commented on docs/go/index.md
> +go install https://github.com/trinsic-id/sdk/go
Thanks!

2022-01-25 01:22 UTC, fundthmcalculus commented on devops/build_sdks.py
> +    doc_path = abspath(join(get_language_dir('docs'), 'reference', 'go'))
Agreed on all counts. My goal is to get the generated docs procedure in place, and then flesh out the content.

2022-01-25 01:30 UTC, fundthmcalculus commented on docs/go/index.md
> +go install https://github.com/trinsic-id/sdk/go
```suggestion
go install github.com/trinsic-id/sdk/go
```

2022-01-25 01:33 UTC, sethjback approved these changes

2022-01-25 01:33 UTC, merged