fix inconsistency in issue from template paramaters
Dentity-Development/dentity-ecosystems-sdk pull request #451
Opened 2022-02-18 20:52 UTC by michaeldboyd

- fixed links, added skeleton for account service
- add account service to toc
- fix issue from template

2022-02-18 20:54 UTC, tmarkovski approved these changes

2022-02-18 22:49 UTC, allibell approved these changes

2022-02-20 16:21 UTC, tmarkovski requested changes

2022-02-20 16:21 UTC, tmarkovski commented on docs/ios/index.md
> +The Trinsic Swift SDK makes it easy to interact with the Trinsic API from any iOS application. You can find the swift install instructions on [Github](https://github.com/trinsic-id/sdk-swift).
```suggestion
The Trinsic Swift SDK makes it easy to interact with the Trinsic API from any application built for iOS, MacCatalyst, or MacOS. The SDK is available for Swift Package Manager and can be added in your dependency section in `Package.swift` as follows:

 ```swift
 dependencies: [
     .package(name: "Trinsic", url: "https://github.com/trinsic-id/sdk-swift", branch: "main")
 ],
 ```

 You can find more details, source code, and tests for the Swift SDK at [Github](https://github.com/trinsic-id/sdk-swift).
```

2022-02-20 16:26 UTC, tmarkovski approved these changes

2022-02-20 16:41 UTC, merged