SDK for Browser
Dentity-Development/dentity-ecosystems-sdk pull request #47
Opened 2021-06-15 20:08 UTC by tmarkovski

PR on behalf of Michael Black

2021-06-15 22:20 UTC, michaeldboyd requested changes

2021-06-15 22:20 UTC, michaeldboyd commented on node/test/ProviderService.test.js
> +  let providerService = new TrinsicProviderService("20.84.208.207:5000");
Can we remove hardcoded default IP from source and use an env var instead?

2021-06-15 22:20 UTC, michaeldboyd commented on node/test/WalletService.test.js
> +    let service = new TrinsicWalletService("20.84.208.207:5000");
use env var

2021-06-15 22:20 UTC, michaeldboyd commented on node/test/WalletService.test.js
> +    let service = new TrinsicWalletService("20.84.208.207:5000");
use env var

2021-06-15 22:20 UTC, michaeldboyd commented on node/test/WalletService.test.js
> +    let walletService = new TrinsicWalletService("20.84.208.207:5000");
use env var

2021-06-15 22:20 UTC, michaeldboyd commented on web/src/proto/AuthService_grpc_web_pb.js
> +/**
Is it standard practice to include the autogenerated proto code and the compiled typescript js files within the sdk source code? Seems these might be better accessed as a build command in the README. Lot's of autogenerated files in our version control now.

2021-06-15 22:20 UTC, michaeldboyd commented on node/test/ProviderService.test.js
> +  let providerService = new TrinsicProviderService("20.84.208.207:5000");
ideally with a force commit to overwrite it from version history

2021-06-15 23:57 UTC, fundthmcalculus commented
I can fix that when I get home. You shouldn't commit auto generated files,
that clutters the history and creates confusion.

On Tue, Jun 15, 2021, 18:20 Michael Boyd ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In node/test/ProviderService.test.js
> <https://github.com/trinsic-id/sdk/pull/47#discussion_r652192320>:
>
> > @@ -28,7 +28,7 @@ const createProfile = async () => {
>  }
>
>  test("make an invitation", async t => {
> -  let providerService = new TrinsicProviderService();
> +  let providerService = new TrinsicProviderService("20.84.208.207:5000");
>
> ideally with a force commit to overwrite it from version history
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/trinsic-id/sdk/pull/47#discussion_r652192320>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AD7QPF5GEZSDIQQ2VZ7XOK3TS7G37ANCNFSM46X6WHJA>
> .
>

2021-06-16 02:58 UTC, fundthmcalculus commented on node/test/WalletService.test.js
> +    let service = new TrinsicWalletService("20.84.208.207:5000");
Can we use a configuration in lieu of an env var?

2021-06-16 02:59 UTC, fundthmcalculus commented on web/src/proto/AuthService_grpc_web_pb.js
> +/**
No we shouldn't. Let me remove that, but add a build step to generate them.

2021-06-16 13:45 UTC, tmarkovski commented on web/src/proto/AuthService_grpc_web_pb.js
> +/**
Ideally we shouldn't, but it's not too terrible that we do. Generating them is easy using the `Generate-Proto.ps1` script, so that can just be added as npm script pre-build.
Generated proto files should also be ignored in .gitignore and generation script which will use `protoc` with a plugin, should run consistently on all platforms, not just CI. Otherwise, it's best to keep the generated files in for now.

2021-06-16 15:50 UTC, michaeldboyd approved these changes

2021-06-16 15:51 UTC, merged