Sdk 479 .NET request/response and status exceptions
Dentity-Development/dentity-ecosystems-sdk pull request #502
Opened 2022-03-22 15:12 UTC by fundthmcalculus

2022-03-22 15:23 UTC, tmarkovski requested changes
Can you please update the tests, so they compile and pass?

2022-03-22 15:25 UTC, fundthmcalculus commented
> Can you please update the tests, so they compile and pass?

`<joke>`Nah, I like a casual test failure. LOL.`</joke>` Obviously I'll fix that. I wanted to get your opinion before I do all the other languages similarly.

2022-03-22 16:19 UTC, tmarkovski commented
I wouldn't put too much work into ensuring the response status is properly handled like `if (response.Status != ResponseStatus.Success)`, as we will most likely change this and roll it into the grpc status code instead, which means the usual server error pipeline.

2022-03-23 11:23 UTC, fundthmcalculus commented
> I wouldn't put too much work into ensuring the response status is properly handled like `if (response.Status != ResponseStatus.Success)`, as we will most likely change this and roll it into the grpc status code instead, which means the usual server error pipeline. The rest of the cleanup is ok.

This was something I kind of thought should be handled at the server level. I won't worry about it for the other languages then.

2022-03-23 13:01 UTC, tmarkovski requested changes

2022-03-23 13:01 UTC, tmarkovski commented on dotnet/Tests/Tests.cs
> +        var itemId = (await walletService.InsertItemAsync(new() {ItemJson = credential.SignedDocumentJson})).ItemId;
Does this code block go in the documentation? If yes, we should reformat it to better syntax, separate the response, etc.

2022-03-23 13:01 UTC, tmarkovski commented on dotnet/Tests/Tests.cs
> +        var itemId = (await walletService.InsertItemAsync(new() {ItemJson = credentialJson.DocumentJson})).ItemId;
Same comment as above

2022-03-23 13:01 UTC, tmarkovski commented on dotnet/Trinsic/WalletService.cs
>              request.Query = "SELECT * FROM c";
Can we change this to `SELECT c.id, c.type, c.data FROM c`? It's a cleaned up version.

2022-03-23 16:54 UTC, fundthmcalculus commented on dotnet/Tests/Tests.cs
> +        var itemId = (await walletService.InsertItemAsync(new() {ItemJson = credential.SignedDocumentJson})).ItemId;
It does, but this is pretty self-explanatory as it is.

2022-03-23 16:59 UTC, fundthmcalculus commented on dotnet/Trinsic/WalletService.cs
>              request.Query = "SELECT * FROM c";
I can make this change everywhere.

2022-03-23 17:14 UTC, tmarkovski commented on dotnet/Tests/Tests.cs
> +        var itemId = (await walletService.InsertItemAsync(new() {ItemJson = credential.SignedDocumentJson})).ItemId;
I know, it's just a bad C# code that I'm not too proud of us suggesting in a docs sample

2022-03-23 17:15 UTC, tmarkovski commented on dotnet/Trinsic/WalletService.cs
>              request.Query = "SELECT * FROM c";
This only applies to Wallet search, not Template or TrustRegistry searches

2022-03-23 22:53 UTC, fundthmcalculus commented on dotnet/Trinsic/WalletService.cs
>              request.Query = "SELECT * FROM c";
General issue here to prevent off-topic or loss: https://github.com/trinsic-id/sdk/issues/504

2022-03-24 00:11 UTC, tmarkovski approved these changes

2022-03-24 00:11 UTC, tmarkovski commented on dotnet/Tests/Tests.cs
> +        var insertItemResponse = (await walletService.InsertItemAsync(new() {ItemJson = credential.SignedDocumentJson}));
```suggestion
        var insertItemResponse = await walletService.InsertItemAsync(new() {ItemJson = credential.SignedDocumentJson});
```

2022-03-24 00:11 UTC, tmarkovski commented on dotnet/Tests/Tests.cs
> +        var insertItemResponse = (await walletService.InsertItemAsync(new() {ItemJson = credentialJson.DocumentJson}));
```suggestion
        var insertItemResponse = await walletService.InsertItemAsync(new() {ItemJson = credentialJson.DocumentJson});
```

2022-03-24 00:12 UTC, merged