Enable navigation tabs in docs top level
Dentity-Development/dentity-ecosystems-sdk pull request #595
Opened 2022-04-21 11:41 UTC by tmarkovski

2022-04-21 12:03 UTC, fundthmcalculus requested changes

2022-04-21 12:03 UTC, fundthmcalculus commented on mkdocs.yml
> +    - navigation.tabs
This breaks the layout that we've been using and makes it more confusing. @michaeldboyd requested this be reverted last time.

2022-04-21 12:21 UTC, tmarkovski commented on mkdocs.yml
> +    - navigation.tabs
@michaeldboyd Can you please shed more light on what layout this breaks? UX wise, top level navigation tabs are a lot more usable and discoverable. It also allows us to one level deeper in the right hand navigation tabs. It also separates the sections conceptually a lot better than having them be bundled in one menu.

2022-04-21 17:49 UTC, geel9 commented on mkdocs.yml
> +    - navigation.tabs
I'm a +1 on top-level tabs

2022-04-22 18:09 UTC, lucasamonrc commented on mkdocs.yml
> +    - navigation.tabs
I like top-level tabs as well. But I also like to be able to navigate using the sidebar when I am reading docs. So why not both?

2022-04-22 18:15 UTC, lucasamonrc commented on mkdocs.yml
> +    - navigation.tabs
I like top-level tabs as well. But I also like to be able to navigate using the sidebar when I am reading docs. So why not both?

2022-04-26 01:36 UTC, geel9 commented on mkdocs.yml
> +    - navigation.tabs
@lucasamonrc The way I envision it would be to have the top-level docs be the root navigation nodes, and the sidebar would be for the navigation nodes that follow from whatever top-level tab you're browsing.

So, if we had "SDK" and "Learn" tabs, the sidebar would be entirely different for each of those tabs.

I think we just have too many things to write about, and we can only feasibly nest the sidebar to a certain extent. Adding the top-level tabs basically gives us one more nesting level, as well as a clean mental (and actual) partition between logical sections.

Our SDK reference doesn't need to share space with our conceptual documentation, IMO. Right now, they're in competition, by virtue of the aforementioned limit of tree depth for the sidebar.

I think right now we're waiting for @michaeldboyd to provide input?

2022-04-26 19:11 UTC, fundthmcalculus approved these changes

2022-04-26 19:11 UTC, fundthmcalculus commented
Let's give this a shot.

2022-04-27 00:30 UTC, lucasamonrc approved these changes

2022-04-28 17:22 UTC, merged