Update repo with latest proto messages. Add verification results to CLI
Dentity-Development/dentity-ecosystems-sdk pull request #601
Opened 2022-04-22 11:37 UTC by tmarkovski

2022-04-22 12:09 UTC, fundthmcalculus commented
I've got some work I'm doing on this. Will take over this PR later.

2022-04-22 17:07 UTC, fundthmcalculus requested changes
Requesting changes to block merge while I fix some other bugs. Will take care of this once #598 is merged.

2022-04-22 20:29 UTC, tmarkovski commented
> Requesting changes to block merge while I fix some other bugs. Will take care of this once #598 is merged.

We will need to build and use the CLI for our IIW Demo next week. Do we want this merged and a hot fix released for the CLI only?

2022-04-23 12:15 UTC, fundthmcalculus approved these changes

2022-04-23 12:15 UTC, merged