Completed walkthrough page
Dentity-Development/dentity-ecosystems-sdk pull request #629
Opened 2022-05-05 16:21 UTC by MichaelEdwardBlack

#422 

Maybe we can move the replit task in this issue to a separate issue.

2022-05-06 15:20 UTC, tmarkovski commented on docs/walkthroughs/vaccination.md
> +            "required": true
This is not an actual field. All items are required by default, unless specified otherwise with `optional` field.

2022-05-06 15:21 UTC, tmarkovski commented on docs/walkthroughs/vaccination.md
> +            "required": true
Here's the template fields schema - https://schema.trinsic.cloud/template/fields

2022-05-06 15:22 UTC, tmarkovski commented on docs/walkthroughs/vaccination.md
> +    trinsic provider create-ecosystem --name "Bobs-Ecosystem" --email bob@example.com --alias bob
```suggestion
    trinsic provider create-ecosystem --name "Bobs-Ecosystem" --email bob@example.com
```

2022-05-06 15:23 UTC, tmarkovski commented
We can punt the replit work for now.

2022-05-12 13:01 UTC, tmarkovski commented on docs/walkthroughs/vaccination.md
> +            "required": true
```suggestion
```

2022-05-12 13:01 UTC, tmarkovski approved these changes

2022-05-17 02:07 UTC, geel9 commented
So, I see the following issues with the walkthrough before we can consider it to be complete:

- The created Template has different fields based on the language. All languages should be building the exact same Template.
- After creation of the Ecosystem, we should explain how to _use_ said Ecosystem.
  - For example, by setting `ServiceOptions.DefaultEcosystem`
- Creation of the Ecosystem should be the _first_ step in the tutorial; before the creation of the accounts. The Accounts, and the Template, need to be created within the Ecosystem.
- Either prepare the Replits and link them, or remove the text about the Replits until they exist.

2022-05-17 02:09 UTC, geel9 commented
I'm comfortable taking on the above issues.

I'd prefer to issue a PR into this branch, and then merge this PR into main, rather than merging this PR immediately.

I'll do that tomorrow (the 17th).

2022-05-17 15:14 UTC, geel9 commented
Upon further review, the issues with the walkthrough are more extensive than I initially thought; I've created a separate tracking issue here: https://github.com/trinsic-id/sdk/issues/659

I'll be merging this PR to clear it from the queue, and will create a new PR against the above issue later.

2022-05-17 15:25 UTC, geel9 requested changes

2022-05-17 15:25 UTC, geel9 commented on docs/walkthroughs/vaccination.md
> +        "name": {
```suggestion
        "firstName": {
```

2022-05-17 15:25 UTC, geel9 commented on docs/walkthroughs/vaccination.md
> +            "description": "Name of the business",
```suggestion
            "description": "First name of vaccine recipient",
```

2022-05-17 15:25 UTC, geel9 commented on docs/walkthroughs/vaccination.md
> +        "website": {
```suggestion
        "lastName": {
```

2022-05-17 15:25 UTC, geel9 commented on docs/walkthroughs/vaccination.md
> +            "description": "More information about the business"
```suggestion
            "description": "Last name of vaccine recipient"
```

2022-05-17 15:25 UTC, geel9 commented on docs/walkthroughs/vaccination.md
> +        "rating":{
```suggestion
        "batchNumber":{
```

2022-05-17 15:25 UTC, geel9 commented on docs/walkthroughs/vaccination.md
> +            "type": "number",
```suggestion
            "type": "string",
```

2022-05-17 15:25 UTC, geel9 commented on docs/walkthroughs/vaccination.md
> +            "description": "rating on scale of 1-10",
```suggestion
            "description": "Batch number of vaccine",
```

2022-05-17 15:25 UTC, geel9 commented on docs/walkthroughs/vaccination.md
> +        "details":{
```suggestion
        "countryOfVaccination":{
```

2022-05-17 15:25 UTC, geel9 commented on docs/walkthroughs/vaccination.md
> +            "description": "An individual's last name",
```suggestion
            "description": "Country in which the subject was vaccinated",
```

2022-05-17 15:27 UTC, geel9 approved these changes

2022-05-17 15:28 UTC, merged