Dart support
Dentity-Development/dentity-ecosystems-sdk pull request #670
Opened 2022-05-24 17:54 UTC by fundthmcalculus

2022-05-25 01:19 UTC, fundthmcalculus commented
Ignore the golang failure, that's a style (`gofmt`) issue which will be addressed in a different PR.

2022-05-26 00:20 UTC, geel9 requested changes

2022-05-26 00:20 UTC, geel9 commented on dart/example/vaccine_example.dart
> +String vaccineCertUnsignedPath() {
The vaccine example needs to be updated in line with https://github.com/trinsic-id/sdk/issues/659

Given that this still needs to happen for Go and Java, though (and the fact that I'm the done that's been making the changes) I wouldn't mind approving this PR now and doing it myself with the others -- good chance to play around with Dart a bit.

2022-05-26 00:20 UTC, geel9 commented on python/samples/vaccine_demo.py
>  from trinsic.account_service import AccountService
I think you need to merge main into your branch

2022-05-26 00:20 UTC, geel9 commented on dart/lib/src/dart_base.dart
> -/// Checks if you are awesome. Spoiler: you are.
This seems to be an erroneous delete -- I'm definitely still awesome.

This is a blocking issue.

2022-05-26 11:14 UTC, fundthmcalculus commented on dart/example/vaccine_example.dart
> +String vaccineCertUnsignedPath() {
I vote you do it. That way, everything is done consistently.

2022-05-26 11:14 UTC, fundthmcalculus commented on python/samples/vaccine_demo.py
>  from trinsic.account_service import AccountService
Yup lol. Will do.

2022-05-26 11:15 UTC, fundthmcalculus commented on dart/lib/src/dart_base.dart
> -/// Checks if you are awesome. Spoiler: you are.
I got you. 😀

2022-05-26 14:06 UTC, geel9 approved these changes

2022-05-26 14:06 UTC, merged