Golang single service
Dentity-Development/dentity-ecosystems-sdk pull request #704
Opened 2022-06-03 16:01 UTC by sethjback

This draft is a proposal for 2 things:

1. Fixing the package namespace issue in the protobuf. Ideally this will be pushed to a separate PR, it is included here simply to make everything work.
2. Creates a `trinsic-service` that wraps all the individual services

This is intended mostly to encourage feedback on the wrapper service

2022-06-05 11:53 UTC, fundthmcalculus commented on go/services/credential_service.go
> +	credentials "github.com/trinsic-id/sdk/go/proto/verifiablecredentials/v1"
I specifically went through the languages and made all services singular, not plural. Is there a reason for this being reverted?

2022-06-05 11:54 UTC, fundthmcalculus approved these changes
In general, I like this. Except for the singular/plural issue, which might just be a personal preference.

2022-06-06 16:48 UTC, sethjback commented on go/services/credential_service.go
> +	credentials "github.com/trinsic-id/sdk/go/proto/verifiablecredentials/v1"
Nope! Singular works - this is just my RESTful instinct coming out....

2022-06-07 17:06 UTC, fundthmcalculus requested changes
Blocking merge until @sethjback has time to confirm I didn't break anything

2022-06-07 17:06 UTC, sethjback commented
Looks good to me

2022-06-07 17:08 UTC, fundthmcalculus approved these changes

2022-06-07 17:08 UTC, merged