Update golang packages
Dentity-Development/dentity-ecosystems-sdk pull request #710
Opened 2022-06-06 22:23 UTC by sethjback

Modifies the SDK `proto` files to change the golang package name, keeping it consistent with the directory layout in `/proto/`.

Updates the generated proto files in `go/proto/` to use the new namespaceing.

Updates the `go/services/` files to use the new imports.

Changing the package names prevents collisions with services that have the same endpoints (e.g. `account.info` and `provider.info`) and allows for language tooling to auto-resolve packages.

2022-06-06 22:54 UTC, fundthmcalculus approved these changes

2022-06-07 14:36 UTC, fundthmcalculus requested changes
Blocking merge until we verify that this is the proper set of proto files with all of @tmarkovski changes from server

2022-06-07 14:36 UTC, tmarkovski approved these changes

2022-06-07 16:01 UTC, fundthmcalculus approved these changes

2022-06-07 16:04 UTC, tmarkovski commented
Minor PR that aligned server with sdk protos - https://github.com/trinsic-id/sdk/pull/712

2022-06-07 16:14 UTC, sethjback commented
Looks good

2022-06-07 16:27 UTC, merged