Create ecosystem proto and implementation changes
Dentity-Development/dentity-ecosystems-sdk pull request #756
Opened 2022-06-15 17:16 UTC by tmarkovski

- dotnet
- cli
- web (ts)

2022-06-15 17:29 UTC, fundthmcalculus commented
I will fix the java issues in a PR, hold on a minute. Do we have an SDK change request in for this set of changes?

2022-06-15 17:33 UTC, tmarkovski commented
You mean an issue? I don't think so. I'll make one.

2022-06-15 17:36 UTC, fundthmcalculus commented
> You mean an issue? I don't think so. I'll make one.

https://github.com/trinsic-id/sdk/issues/759 <- thanks! Will do this as a set of PRs into this one, and we can merge all at once.

2022-06-15 17:39 UTC, fundthmcalculus requested changes

2022-06-15 17:39 UTC, fundthmcalculus commented on dotnet/Trinsic/ProviderService.cs
> +            : await Client.CreateEcosystemAsync(request);
This change needs replicated.

2022-06-15 17:39 UTC, fundthmcalculus commented on proto/services/account/v1/account.proto
> +// Authorize ecosystem to receive wallet envents
```suggestion
// Authorize ecosystem to receive wallet events
```

2022-06-15 17:39 UTC, fundthmcalculus commented on web/src/ProviderService.ts
> +      : this.client.createEcosystem(request);
This needs replicated

2022-06-15 17:40 UTC, fundthmcalculus commented
Made a quick typo fix in a proto comment, will merge new generated protos PR in. Other comments about "this needs replicated" are for my own reference, don't close, and nothing to fix.

2022-06-16 16:06 UTC, fundthmcalculus approved these changes

2022-06-16 16:52 UTC, merged