Update Production Package Testing to 1.6.0
Dentity-Development/dentity-ecosystems-sdk pull request #825
Opened 2022-06-30 15:35 UTC by fundthmcalculus

2022-07-01 16:12 UTC, geel9 requested changes

2022-07-01 16:12 UTC, geel9 commented on python/trinsic/__main__.py
> +from asyncio import set_event_loop_policy
```suggestion
from trinsic.trinsic_util import set_event_loop_policy
```

2022-07-05 17:25 UTC, fundthmcalculus commented
node will continue to fail for reasons related to: https://github.com/trinsic-id/sdk/issues/838

2022-07-05 17:53 UTC, geel9 commented
This PR breaks our docs by removing `sample_demo.py`, which is imported here:

https://docs-v2.trinsic.id/python/

Given that we have the python test script that can be executed via CLI, approval for me to commit to this branch removing this injection @fundthmcalculus?

2022-07-05 17:54 UTC, fundthmcalculus commented
Go for it. Thanks!

2022-07-05 17:56 UTC, geel9 approved these changes

2022-07-05 17:56 UTC, merged